### ISSUE TITLE
Make URL more navigatable

### ISSUE THREAD

**Issue by mattfarina** [SUSE/bci-docs#34]
If you go to https://opensource.suse.com/BCI-docs/ it works. But, if you go to https://opensource.suse.com/bci-docs/ it doesn't. Notice the case difference. I would expect most people who type the URL will use lowercase.

Can we get this fixed? If not to work for both upper and lower to work for just lowercase.

**Comment by dcermak** [comment]
This is a limitation/feature with github pages: they are case sensitive, so we can only fix this by renaming the repository. I have done that now, but now the uppercase url will cease working.
